spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true

slack:
  token: xoxb-2070788189600-4701637872135-DTWPG4iKuJjb2VtbQhidWKmA
  channel:
    customer:
      monitor: '#03-allen-customer-alarm-javaAndDining'
    owner:
      monitor: '#03-allen-owner-alarm-javaAndDining'

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: TRACE