spring:
  profiles:
    active: release
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: TRACE
---

spring:
  config:
    activate:
      on-profile: release
  flyway:
    enabled: true
    baselineOnMigrate: true
    url: jdbc:mysql://localhost:3306/dining
    user: root
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/dining
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        dbc:
          lob:
            non_contextual_creation: true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true